function [ i ] = Get_Input(  )
%   This function display menu options and get an input

    clc
    list = {"Open an image file", ...
            "Calibrate axis", ...
            "Acquire data manually", ...
            "Acquire data automatically", ...
            "View and sort data", ...
            "Clear data", ...
            "Exit"};
    i = listdlg('ListString', list, 'SelectionMode', 'single', 'ListSize', [250, 300]);
    if (isempty(i))
        i = 7;
    end

end

